env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false
  TERM: dumb
jobs:
  promote:
    container: ghcr.io/menny/android_base:1.20.0
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4.1.1
      with:
        ref: ${{ matrix.refname }}
    - continue-on-error: true
      name: request-scheduled-promote
      uses: ./.github/actions/deploy-request
      with:
        api_token: ${{ secrets.BOT_MASTER_RW_GITHUB_TOKEN }}
        api_username: ${{ secrets.BOT_MASTER_RW_GITHUB_USERNAME }}
        new_deploy: false
        ref: ${{ matrix.refname }}
        sha: HEAD
    strategy:
      fail-fast: false
      matrix:
        refname:
        - main
        - release-branch-addons-v5.0-r1
name: deployment-promote
on:
  repository_dispatch:
    types: trigger-ga___deployment_promote.yml
