env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false
  GRADLE_USER_HOME: .github_cache_gradle/
  TERM: dumb
jobs:
  deploy:
    container: ghcr.io/menny/android_ndk:1.20.0
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4.1.1
      with:
        token: ${{ secrets.BOT_MASTER_RW_GITHUB_TOKEN }}
    - continue-on-error: true
      uses: actions/checkout@v4.1.1
      with:
        path: ${{ secrets.SECRETS_REPOSITORY_FOLDER }}
        ref: main
        repository: ${{ secrets.SECRETS_REPOSITORY }}
        token: ${{ secrets.BOT_SECRETS_R_GITHUB_TOKEN }}
    - continue-on-error: true
      env:
        GITHUB_CONTEXT_JSON: ${{ toJson(github) }}
      name: setup
      run: './scripts/ci/ci_setup.sh

        mkdir -p outputs/apk || true

        mkdir -p outputs/bundle || true

        mkdir -p outputs/fdroid || true

        mkdir -p ime/app/build/outputs/mapping || true

        '
    - continue-on-error: true
      uses: actions/upload-artifact@v4.3.2
      with:
        name: github_object
        path: build/github_object
    - continue-on-error: true
      name: status-in-progress
      run: "./gradlew --stacktrace :deployment:updateDeploymentState \\\n  -PRequest.apiUsername=\"\
        ${{ secrets.BOT_MASTER_RW_GITHUB_USERNAME }}\" \\\n  -PRequest.apiUserToken=\"\
        ${{ secrets.BOT_MASTER_RW_GITHUB_TOKEN }}\" \\\n  -PrequestStatus.environment=\"\
        ${{ github.event.deployment.environment }}\" \\\n  -PrequestStatus.deployment_id=\"\
        ${{ github.event.deployment.id }}\" \\\n  -PrequestStatus.deployment_state=\"\
        in_progress\"\n"
    - continue-on-error: true
      uses: ./.github/actions/deploy
      with:
        crash_report_email: ${{ secrets.ANYSOFTKEYBOARD_CRASH_REPORT_EMAIL }}
        deployment_environment: ${{ github.event.deployment.environment }}
        deployment_task: ${{ github.event.deployment.task }}
        keystore_key_password: ${{ secrets.ANYSOFTKEYBOARD_KEYSTORE_KEY_PASSWORD }}
        keystore_password: ${{ secrets.ANYSOFTKEYBOARD_KEYSTORE_PASSWORD }}
        previous_deployment_environment: ${{ github.event.deployment.payload.previous_environment
          }}
        secrets_repo_folder: ${{ secrets.SECRETS_REPOSITORY_FOLDER }}
    - continue-on-error: true
      name: status-success
      run: "./gradlew --stacktrace :deployment:updateDeploymentSuccess \\\n  -PRequest.apiUsername=\"\
        ${{ secrets.BOT_MASTER_RW_GITHUB_USERNAME }}\" \\\n  -PRequest.apiUserToken=\"\
        ${{ secrets.BOT_MASTER_RW_GITHUB_TOKEN }}\" \\\n  -PrequestStatus.environment=\"\
        ${{ github.event.deployment.environment }}\" \\\n  -PrequestStatus.deployment_id=\"\
        ${{ github.event.deployment.id }}\" \\\n  -PrequestStatus.environment=\"${{\
        \ github.event.deployment.environment }}\" \\\n  -PrequestStatus.sha=\"${{\
        \ github.event.deployment.sha }}\"\n"
    - continue-on-error: true
      if: failure()
      name: status-failure
      run: "./gradlew --stacktrace :deployment:updateDeploymentState \\\n  -PRequest.apiUsername=\"\
        ${{ secrets.BOT_MASTER_RW_GITHUB_USERNAME }}\" \\\n  -PRequest.apiUserToken=\"\
        ${{ secrets.BOT_MASTER_RW_GITHUB_TOKEN }}\" \\\n  -PrequestStatus.environment=\"\
        ${{ github.event.deployment.environment }}\" \\\n  -PrequestStatus.deployment_id=\"\
        ${{ github.event.deployment.id }}\" \\\n  -PrequestStatus.deployment_state=\"\
        failure\"\n"
    - continue-on-error: true
      if: always()
      uses: actions/upload-artifact@v4.3.2
      with:
        name: deploy-logging
        path: build/build-logging
    - continue-on-error: true
      if: always()
      uses: actions/upload-artifact@v4.3.2
      with:
        name: bundles
        path: outputs/bundle
    - continue-on-error: true
      if: always()
      uses: actions/upload-artifact@v4.3.2
      with:
        name: apks
        path: outputs/apk
    - continue-on-error: true
      if: always()
      uses: actions/upload-artifact@v4.3.2
      with:
        name: proguard-mapping
        path: ime/app/build/outputs/mapping
    - continue-on-error: true
      if: always()
      uses: actions/upload-artifact@v4.3.2
      with:
        name: fdroid-metadata
        path: outputs/fdroid
    timeout-minutes: 40
name: deployment
on:
  repository_dispatch:
    types: trigger-ga___deploy.yml
