env:
  TERM: dumb
  TMPDIR: /tmp
jobs:
  aosp-dictionaries-update:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4.1.1
    - continue-on-error: true
      uses: pnpm/action-setup@v3.0.0
      with:
        run_install: true
        version: 8.6.9
    - continue-on-error: true
      uses: actions/setup-node@v4.0.2
      with:
        cache: pnpm
        node-version-file: .nvmrc
    - continue-on-error: true
      run: pnpm build
    - continue-on-error: true
      name: fix git permissions for creating a PR
      run: git config --global --add safe.directory "${PWD}"
    - continue-on-error: true
      name: update AOSP dictionaries
      run: "node dist/update_aosp_dictionaries/index.js update \\\n  --repository_root\
        \ \"${PWD}\" \\\n  --dictionaries_archive https://android.googlesource.com/platform/packages/inputmethods/LatinIME/+archive/refs/heads/main/dictionaries.tar.gz\
        \ \\\n  --dictionaries_mapping \"${PWD}/js/upadte_aosp_dictionaries/aosp_mapping.yml\"\
        \n"
    - continue-on-error: true
      name: update LineageOS dictionaries
      run: "node dist/upadte_aosp_dictionaries/index.js update \\\n  --repository_root\
        \ \"${PWD}\" \\\n  --dictionaries_archive https://github.com/LineageOS/android_packages_inputmethods_LatinIME/archive/refs/heads/lineage-21.0.tar.gz\
        \ \\\n  --dictionaries_mapping \"${PWD}/js/upadte_aosp_dictionaries/lineage_mapping.yml\"\
        \n"
    - continue-on-error: true
      name: Create pull request
      uses: peter-evans/create-pull-request@v6.0.4
      with:
        author: Polyglot <ask@evendanan.net>
        body: Generated from latest objects in AOSP main branch.
        branch: bot-pr/aosp-dict-update
        commit-message: Automated AOSP Dictionaries Update
        committer: Polyglot <ask@evendanan.net>
        delete-branch: true
        team-reviewers: maintainers
        title: Automated AOSP Dictionaries Update
        token: ${{ secrets.BOT_MASTER_RW_GITHUB_TOKEN }}
name: update-aosp-dictionaries
on:
  repository_dispatch:
    types: trigger-ga___update_aosp_dictionaries.yml
